version: '3.7'

networks: 
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

services:
  nodered:
    #image: nodered
    image: 192.87.106.18:56001/nodered:0.1
    deploy:
      replicas: 1
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/data:/data
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/data
    ports:
      - $STACK_PORT:1880
    configs:
      - source: nodered_conf
        target: /data/settings.js
#        uid: node-red
#        gid: node-red

configs:
  nodered_conf:
    external: true
